card.addEventListener("click", function() {
  audio.currentTime = 0;
  audio.play();
});

document.addEventListener("click", function(e) {
  const emojis = ["💢", "‼️", "💥", "🖕🏻", "☠️"];
  const randomEmoji = emojis[Math.floor(Math.random() * emojis.length)];

  const emoji = document.createElement("div");
  emoji.textContent = randomEmoji;
  emoji.style.position = "absolute";
  emoji.style.left = e.pageX + "px";
  emoji.style.top = e.pageY + "px";
  emoji.style.fontSize = "24px";
  emoji.style.pointerEvents = "none";
  emoji.style.transition = "all 2s ease";
  emoji.style.opacity = "1";

  document.body.appendChild(emoji);

  setTimeout(() => {
    emoji.style.top = e.pageY - 80 + "px"; // naik lebih tinggi
    emoji.style.opacity = "0";
  }, 10);

  setTimeout(() => {
    emoji.remove();
  }, 2000); 
});
